<a href="https://colab.research.google.com/github/vblancoOR/econometria/blob/main/Practica_MCO_Estimacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd #librerÃ­a para manejo de datos

datos= pd.read_csv("https://rtgodwin.com/data/houseprice.csv") #Lee base de datos de web...

datos.columns

Index(['Price', 'Lot.Size', 'Waterfront', 'Age', 'Land.Value', 'New.Construct',
       'Central.Air', 'Fuel.Type', 'Heat.Type', 'Sewer.Type', 'Living.Area',
       'Pct.College', 'Bedrooms', 'Fireplaces', 'Bathrooms', 'Rooms'],
      dtype='object')

In [12]:
import statsmodels.api as sm


y = datos["Price"]
X = datos[['Lot.Size', 'Waterfront', 'Age', 'Land.Value', 'New.Construct',
       'Central.Air', 'Living.Area',
       'Pct.College', 'Bedrooms', 'Fireplaces', 'Bathrooms', 'Rooms']]

mco = sm.OLS(y, sm.add_constant(X)).fit()

print(mco.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Price   R-squared:                       0.651
Model:                            OLS   Adj. R-squared:                  0.649
Method:                 Least Squares   F-statistic:                     266.6
Date:                Tue, 15 Oct 2024   Prob (F-statistic):               0.00
Time:                        18:07:45   Log-Likelihood:                -21409.
No. Observations:                1728   AIC:                         4.284e+04
Df Residuals:                    1715   BIC:                         4.292e+04
Df Model:                          12
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const          1.798e+04   9582.728      1.877      0.061    -811.728    3.68e+04
Lot.Size       6973.7396   2052.803      3.397      0.001    2947.477     1.1e+04
Waterfront     1.197e+05   1.55e+04      7.733      0.000    8.94e+04     1.5e+05
Age            -148.2789     54.963     -2.698      0.007    -256.080     -40.478
Land.Value        0.9286      0.047     19.736      0.000       0.836       1.021
New.Construct -4.279e+04   7264.890     -5.890      0.000    -5.7e+04   -2.85e+04
Central.Air    1.324e+04   3304.593      4.008      0.000    6762.053    1.97e+04
Living.Area      69.9725      4.616     15.157      0.000      60.918      79.027
Pct.College    -109.6138    148.714     -0.737      0.461    -401.293     182.066
Bedrooms      -7575.1993   2536.892     -2.986      0.003   -1.26e+04   -2599.470
Fireplaces      926.6228   2978.134      0.311      0.756   -4914.536    6767.781
Bathrooms       2.28e+04   3331.684      6.843      0.000    1.63e+04    2.93e+04
Rooms          3117.1592    962.439      3.239      0.001    1229.482    5004.836
==============================================================================
Omnibus:                      600.968   Durbin-Watson:                   1.674
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4833.919
Skew:                           1.403   Prob(JB):                         0.00
Kurtosis:                      10.698   Cond. No.                     5.46e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.46e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [13]:
datos

,Price,Lot.Size,Waterfront,Age,Land.Value,New.Construct,Central.Air,Fuel.Type,Heat.Type,Sewer.Type,Living.Area,Pct.College,Bedrooms,Fireplaces,Bathrooms,Rooms
0,132500,0.09,0,42,50000,0,0,Electric,Electric,Private,906,35,2,1,1.0,5
1,181115,0.92,0,0,22300,0,0,Gas,Hot Water,Private,1953,51,3,0,2.5,6
2,109000,0.19,0,133,7300,0,0,Gas,Hot Water,Public,1944,51,4,1,1.0,8
3,155000,0.41,0,13,18700,0,0,Gas,Hot Air,Private,1944,51,3,1,1.5,5
4,86060,0.11,0,0,15000,1,1,Gas,Hot Air,Public,840,51,2,0,1.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1723,289000,0.38,0,32,24200,0,0,Gas,Hot Water,Public,2310,61,5,1,2.5,11
1724,285000,0.94,0,37,36200,0,0,Gas,Hot Water,Public,2564,61,4,1,2.5,11
1725,194900,0.39,0,9,20400,0,0,Gas,Hot Air,Public,1099,51,2,0,1.0,3
1726,125000,0.24,0,48,16800,0,0,Gas,Hot Air,Public,1225,51,3,1,1.0,7
1727,111300,0.59,0,86,26000,0,0,Gas,Hot Air,Private,1959,51,3,0,1.0,6

In [17]:
import numpy as np

datos["logPrecio"] = np.log(datos["Price"])
datos["logLandValue"] = np.log(datos["Land.Value"])

In [16]:
y = datos["logPrecio"]
X = datos[['Lot.Size', 'Waterfront', 'Age', 'Land.Value', 'New.Construct',
       'Central.Air', 'Living.Area',
       'Pct.College', 'Bedrooms', 'Fireplaces', 'Bathrooms', 'Rooms']]

mco = sm.OLS(y, sm.add_constant(X)).fit()

print(mco.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              logPrecio   R-squared:                       0.579
Model:                            OLS   Adj. R-squared:                  0.576
Method:                 Least Squares   F-statistic:                     196.9
Date:                Tue, 15 Oct 2024   Prob (F-statistic):          7.55e-312
Time:                        18:24:17   Log-Likelihood:                -333.99
No. Observations:                1728   AIC:                             694.0
Df Residuals:                    1715   BIC:                             764.9
Df Model:                          12
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            11.1634      0.048    230.713      0.000      11.069      11.258
Lot.Size          0.0383      0.010      3.699      0.000       0.018       0.059
Waterfront        0.4792      0.078      6.131      0.000       0.326       0.633
Age              -0.0013      0.000     -4.531      0.000      -0.002      -0.001
Land.Value     3.399e-06   2.38e-07     14.306      0.000    2.93e-06    3.86e-06
New.Construct    -0.1457      0.037     -3.973      0.000      -0.218      -0.074
Central.Air       0.0546      0.017      3.271      0.001       0.022       0.087
Living.Area       0.0003   2.33e-05     11.929      0.000       0.000       0.000
Pct.College       0.0013      0.001      1.765      0.078      -0.000       0.003
Bedrooms          0.0191      0.013      1.493      0.136      -0.006       0.044
Fireplaces        0.0050      0.015      0.334      0.739      -0.024       0.035
Bathrooms         0.1072      0.017      6.374      0.000       0.074       0.140
Rooms             0.0078      0.005      1.606      0.109      -0.002       0.017
==============================================================================
Omnibus:                     1017.626   Durbin-Watson:                   1.579
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            39160.695
Skew:                          -2.135   Prob(JB):                         0.00
Kurtosis:                      25.927   Cond. No.                     5.46e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.46e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [18]:
y = datos["Price"]
X = datos[['Lot.Size', 'Waterfront', 'Age', 'logLandValue', 'New.Construct',
       'Central.Air', 'Living.Area',
       'Pct.College', 'Bedrooms', 'Fireplaces', 'Bathrooms', 'Rooms']]

mco = sm.OLS(y, sm.add_constant(X)).fit()

print(mco.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Price   R-squared:                       0.620
Model:                            OLS   Adj. R-squared:                  0.617
Method:                 Least Squares   F-statistic:                     233.0
Date:                Tue, 15 Oct 2024   Prob (F-statistic):               0.00
Time:                        18:31:21   Log-Likelihood:                -21483.
No. Observations:                1728   AIC:                         4.299e+04
Df Residuals:                    1715   BIC:                         4.306e+04
Df Model:                          12
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const         -1.908e+05   1.57e+04    -12.123      0.000   -2.22e+05    -1.6e+05
Lot.Size       6115.8593   2145.133      2.851      0.004    1908.507    1.03e+04
Waterfront     1.411e+05   1.61e+04      8.789      0.000     1.1e+05    1.73e+05
Age             -32.2712     56.928     -0.567      0.571    -143.926      79.384
logLandValue   2.604e+04   1768.328     14.728      0.000    2.26e+04    2.95e+04
New.Construct -3.012e+04   7508.432     -4.011      0.000   -4.48e+04   -1.54e+04
Central.Air    1.716e+04   3434.251      4.997      0.000    1.04e+04    2.39e+04
Living.Area      79.2284      4.756     16.659      0.000      69.901      88.556
Pct.College    -652.5960    169.289     -3.855      0.000    -984.631    -320.561
Bedrooms      -1.183e+04   2633.869     -4.491      0.000    -1.7e+04   -6664.076
Fireplaces     -574.0962   3108.906     -0.185      0.854   -6671.743    5523.551
Bathrooms      2.372e+04   3478.918      6.819      0.000    1.69e+04    3.05e+04
Rooms          3314.2895   1004.371      3.300      0.001    1344.369    5284.210
==============================================================================
Omnibus:                      633.755   Durbin-Watson:                   1.628
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5024.449
Skew:                           1.501   Prob(JB):                         0.00
Kurtosis:                      10.796   Cond. No.                     2.05e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.05e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [19]:
y = datos["logPrecio"]
X = datos[['Lot.Size', 'Waterfront', 'Age', 'logLandValue', 'New.Construct',
       'Central.Air', 'Living.Area',
       'Pct.College', 'Bedrooms', 'Fireplaces', 'Bathrooms', 'Rooms']]

mco = sm.OLS(y, sm.add_constant(X)).fit()

print(mco.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              logPrecio   R-squared:                       0.580
Model:                            OLS   Adj. R-squared:                  0.577
Method:                 Least Squares   F-statistic:                     197.4
Date:                Tue, 15 Oct 2024   Prob (F-statistic):          2.25e-312
Time:                        18:34:27   Log-Likelihood:                -332.76
No. Observations:                1728   AIC:                             691.5
Df Residuals:                    1715   BIC:                             762.4
Df Model:                          12
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            10.2069      0.076    134.159      0.000      10.058      10.356
Lot.Size          0.0334      0.010      3.221      0.001       0.013       0.054
Waterfront        0.5296      0.078      6.822      0.000       0.377       0.682
Age              -0.0009      0.000     -3.105      0.002      -0.001      -0.000
logLandValue      0.1231      0.009     14.401      0.000       0.106       0.140
New.Construct    -0.1162      0.036     -3.202      0.001      -0.187      -0.045
Central.Air       0.0646      0.017      3.891      0.000       0.032       0.097
Living.Area       0.0003    2.3e-05     13.022      0.000       0.000       0.000
Pct.College      -0.0018      0.001     -2.216      0.027      -0.003      -0.000
Bedrooms          0.0047      0.013      0.366      0.714      -0.020       0.030
Fireplaces       -0.0015      0.015     -0.101      0.919      -0.031       0.028
Bathrooms         0.1124      0.017      6.681      0.000       0.079       0.145
Rooms             0.0082      0.005      1.693      0.091      -0.001       0.018
==============================================================================
Omnibus:                     1014.563   Durbin-Watson:                   1.553
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            41519.171
Skew:                          -2.105   Prob(JB):                         0.00
Kurtosis:                      26.642   Cond. No.                     2.05e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.05e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [20]:
datos.columns

Index(['Price', 'Lot.Size', 'Waterfront', 'Age', 'Land.Value', 'New.Construct',
       'Central.Air', 'Fuel.Type', 'Heat.Type', 'Sewer.Type', 'Living.Area',
       'Pct.College', 'Bedrooms', 'Fireplaces', 'Bathrooms', 'Rooms',
       'logPrecio', 'logLandValue'],
      dtype='object')

In [21]:
dummies = pd.get_dummies(datos["Fuel.Type"], dtype="int", drop_first=True)
datos = pd.concat([datos, dummies], axis=1)
dummies = pd.get_dummies(datos["Heat.Type"], dtype="int", drop_first=True)
datos = pd.concat([datos, dummies], axis=1)
dummies = pd.get_dummies(datos["Sewer.Type"], dtype="int", drop_first=True)
datos = pd.concat([datos, dummies], axis=1)

datos

,Price,Lot.Size,Waterfront,Age,Land.Value,New.Construct,Central.Air,Fuel.Type,Heat.Type,Sewer.Type,...,Bathrooms,Rooms,logPrecio,logLandValue,Gas,Oil,Hot Air,Hot Water,Private,Public
0,132500,0.09,0,42,50000,0,0,Electric,Electric,Private,...,1.0,5,11.794338,10.819778,0,0,0,0,1,0
1,181115,0.92,0,0,22300,0,0,Gas,Hot Water,Private,...,2.5,6,12.106887,10.012342,1,0,0,1,1,0
2,109000,0.19,0,133,7300,0,0,Gas,Hot Water,Public,...,1.0,8,11.599103,8.895630,1,0,0,1,0,1
3,155000,0.41,0,13,18700,0,0,Gas,Hot Air,Private,...,1.5,5,11.951180,9.836279,1,0,1,0,1,0
4,86060,0.11,0,0,15000,1,1,Gas,Hot Air,Public,...,1.0,3,11.362800,9.615805,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1723,289000,0.38,0,32,24200,0,0,Gas,Hot Water,Public,...,2.5,11,12.574182,10.094108,1,0,0,1,0,1
1724,285000,0.94,0,37,36200,0,0,Gas,Hot Water,Public,...,2.5,11,12.560244,10.496814,1,0,0,1,0,1
1725,194900,0.39,0,9,20400,0,0,Gas,Hot Air,Public,...,1.0,3,12.180242,9.923290,1,0,1,0,0,1
1726,125000,0.24,0,48,16800,0,0,Gas,Hot Air,Public,...,1.0,7,11.736069,9.729134,1,0,1,0,0,1
1727,111300,0.59,0,86,26000,0,0,Gas,Hot Air,Private,...,1.0,6,11.619985,10.165852,1,0,1,0,1,0

In [22]:
datos.columns

Index(['Price', 'Lot.Size', 'Waterfront', 'Age', 'Land.Value', 'New.Construct',
       'Central.Air', 'Fuel.Type', 'Heat.Type', 'Sewer.Type', 'Living.Area',
       'Pct.College', 'Bedrooms', 'Fireplaces', 'Bathrooms', 'Rooms',
       'logPrecio', 'logLandValue', 'Gas', 'Oil', 'Hot Air', 'Hot Water',
       'Private', 'Public'],
      dtype='object')

In [24]:
y = datos["Price"]
X = datos[['Lot.Size', 'Waterfront', 'Age', 'Land.Value', 'New.Construct',
       'Central.Air', 'Living.Area',
       'Pct.College', 'Bedrooms', 'Fireplaces', 'Bathrooms', 'Rooms', 'Gas', 'Oil', 'Hot Air', 'Hot Water',
       'Private', 'Public']]

mco = sm.OLS(y, sm.add_constant(X)).fit()

print(mco.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Price   R-squared:                       0.653
Model:                            OLS   Adj. R-squared:                  0.650
Method:                 Least Squares   F-statistic:                     179.0
Date:                Tue, 15 Oct 2024   Prob (F-statistic):               0.00
Time:                        18:44:27   Log-Likelihood:                -21403.
No. Observations:                1728   AIC:                         4.284e+04
Df Residuals:                    1709   BIC:                         4.295e+04
Df Model:                          18
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const          9258.7471   1.96e+04      0.472      0.637   -2.92e+04    4.77e+04
Lot.Size       7599.4489   2241.141      3.391      0.001    3203.780     1.2e+04
Waterfront     1.202e+05   1.55e+04      7.734      0.000    8.97e+04    1.51e+05
Age            -130.4459     58.386     -2.234      0.026    -244.962     -15.929
Land.Value        0.9219      0.048     19.379      0.000       0.829       1.015
New.Construct -4.544e+04   7307.590     -6.219      0.000   -5.98e+04   -3.11e+04
Central.Air    9953.0912   3478.139      2.862      0.004    3131.232    1.68e+04
Living.Area      69.9595      4.615     15.159      0.000      60.908      79.011
Pct.College    -110.1593    151.462     -0.727      0.467    -407.230     186.912
Bedrooms      -7835.1918   2567.321     -3.052      0.002   -1.29e+04   -2799.768
Fireplaces     1036.6134   2985.866      0.347      0.729   -4819.725    6892.951
Bathrooms      2.311e+04   3369.674      6.859      0.000    1.65e+04    2.97e+04
Rooms          3019.7608    961.905      3.139      0.002    1133.125    4906.396
Gas            1.093e+04   1.21e+04      0.901      0.368   -1.29e+04    3.47e+04
Oil            6550.4708   1.29e+04      0.508      0.611   -1.87e+04    3.18e+04
Hot Air          82.4519   1.23e+04      0.007      0.995   -2.41e+04    2.42e+04
Hot Water     -1.037e+04   1.28e+04     -0.808      0.419   -3.56e+04    1.48e+04
Private        4845.1066   1.71e+04      0.283      0.777   -2.87e+04    3.84e+04
Public         3321.1679   1.71e+04      0.195      0.846   -3.02e+04    3.68e+04
==============================================================================
Omnibus:                      599.292   Durbin-Watson:                   1.658
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4839.208
Skew:                           1.397   Prob(JB):                         0.00
Kurtosis:                      10.707   Cond. No.                     1.05e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.05e+06. This might indicate that there are
strong multicollinearity or other numerical problems.